services:
    _defaults:
        autowire: true
        autoconfigure: true

    OHMedia\TeamBundle\:
        resource: '../src/'
        exclude:
            - '../src/Entity/'
            - '../src/OHMediaTeamBundle.php'
